[2017-08-31 11:12:19] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:12:19] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:12:19] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:12:19] application.DEBUG: < 404 [] []
[2017-08-31 11:15:50] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:15:50] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:15:50] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:15:50] application.DEBUG: < 404 [] []
[2017-08-31 11:21:34] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:21:34] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:21:34] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:21:34] application.DEBUG: < 404 [] []
[2017-08-31 11:22:55] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:22:55] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:22:55] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:22:55] application.DEBUG: < 404 [] []
[2017-08-31 11:29:21] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:29:21] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:29:21] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:29:21] application.DEBUG: < 404 [] []
[2017-08-31 11:30:25] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:30:25] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:30:25] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:30:25] application.DEBUG: < 404 [] []
[2017-08-31 11:36:25] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:36:25] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:36:25] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:36:25] application.DEBUG: < 404 [] []
[2017-08-31 11:40:48] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:40:48] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:40:48] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:40:48] application.DEBUG: < 404 [] []
[2017-08-31 11:41:43] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:41:43] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:41:43] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:41:43] application.DEBUG: < 404 [] []
[2017-08-31 11:45:10] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:45:10] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:45:10] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:45:10] application.DEBUG: < 404 [] []
[2017-08-31 11:45:16] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 11:45:16] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 11:45:16] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 11:45:16] application.DEBUG: < 404 [] []
[2017-08-31 12:48:43] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 12:48:43] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 12:48:43] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 12:48:43] application.DEBUG: < 404 [] []
[2017-08-31 12:50:17] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 12:50:17] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 12:50:17] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 12:50:17] application.DEBUG: < 404 [] []
[2017-08-31 12:55:20] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 12:55:20] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 12:55:20] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 12:55:20] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-31 12:55:20] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 12:55:20] application.DEBUG: < 404 [] []
[2017-08-31 12:55:20] application.DEBUG: < 200 [] []
[2017-08-31 12:55:23] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 12:55:23] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 12:55:23] application.DEBUG: < 200 [] []
[2017-08-31 12:55:28] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 12:55:28] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 12:55:28] application.DEBUG: < 200 [] []
[2017-08-31 12:55:31] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 12:55:31] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 12:55:31] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 12:55:31] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-31 12:55:31] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 12:55:31] application.DEBUG: < 200 [] []
[2017-08-31 12:55:31] application.DEBUG: < 404 [] []
[2017-08-31 12:55:36] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"2","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/2","method":"GET"} []
[2017-08-31 12:55:36] application.DEBUG: > GET /courses/page/2 [] []
[2017-08-31 12:55:36] application.DEBUG: < 200 [] []
[2017-08-31 12:55:38] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"3","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/3","method":"GET"} []
[2017-08-31 12:55:38] application.DEBUG: > GET /courses/page/3 [] []
[2017-08-31 12:55:38] application.DEBUG: < 200 [] []
[2017-08-31 12:55:50] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-31 12:55:50] application.DEBUG: > GET /courses [] []
[2017-08-31 12:55:50] application.DEBUG: < 200 [] []
[2017-08-31 13:10:48] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:10:48] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:10:48] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:10:48] application.DEBUG: < 404 [] []
[2017-08-31 13:16:42] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:16:42] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:16:42] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:16:42] application.DEBUG: < 404 [] []
[2017-08-31 13:19:18] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:19:18] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:19:18] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:19:18] application.DEBUG: < 404 [] []
[2017-08-31 13:30:02] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:30:02] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:30:02] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:30:02] application.DEBUG: < 404 [] []
[2017-08-31 13:36:53] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:36:53] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:36:53] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:36:53] application.DEBUG: < 404 [] []
[2017-08-31 13:40:39] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:40:39] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:40:39] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:40:39] application.DEBUG: < 404 [] []
[2017-08-31 13:45:53] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:45:53] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:45:53] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:45:53] application.DEBUG: < 404 [] []
[2017-08-31 13:47:27] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:47:27] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:47:27] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:47:27] application.DEBUG: < 404 [] []
[2017-08-31 13:50:47] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:50:47] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:50:47] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:50:47] application.DEBUG: < 404 [] []
[2017-08-31 13:51:08] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 13:51:08] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 13:51:08] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 13:51:08] application.DEBUG: < 404 [] []
[2017-08-31 14:03:09] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 14:03:09] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 14:03:09] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 14:03:09] application.DEBUG: < 404 [] []
[2017-08-31 14:05:01] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 14:05:01] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 14:05:01] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 14:05:01] application.DEBUG: < 404 [] []
[2017-08-31 14:08:51] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 14:08:51] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 14:08:51] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 14:08:51] application.DEBUG: < 404 [] []
[2017-08-31 14:09:05] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 14:09:05] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 14:09:05] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 14:09:05] application.DEBUG: < 404 [] []
[2017-08-31 14:31:30] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 14:31:30] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 14:31:30] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 14:31:30] application.DEBUG: < 404 [] []
[2017-08-31 14:40:43] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 14:40:43] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 14:40:43] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 14:40:43] application.DEBUG: < 404 [] []
[2017-08-31 19:58:50] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"3","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/3","method":"GET"} []
[2017-08-31 19:58:50] application.DEBUG: > GET /courses/page/3 [] []
[2017-08-31 19:58:50] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 19:58:50] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-31 19:58:50] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 19:58:50] application.DEBUG: < 404 [] []
[2017-08-31 19:58:50] application.DEBUG: < 200 [] []
[2017-08-31 19:58:50] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (from "http://localhost:8000/courses/page/3") (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/courses/page/3\") at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 19:58:50] application.ERROR: No route found for "GET /favicon.ico" (from "http://localhost:8000/courses/page/3") [] []
[2017-08-31 19:58:50] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 19:58:50] application.DEBUG: < 404 [] []
[2017-08-31 19:58:59] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-31 19:58:59] application.DEBUG: > GET /courses [] []
[2017-08-31 19:58:59] application.DEBUG: < 200 [] []
[2017-08-31 20:13:16] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:13:16] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:13:16] application.DEBUG: < 200 [] []
[2017-08-31 20:14:08] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:14:08] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:14:08] application.DEBUG: < 200 [] []
[2017-08-31 20:14:19] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 20:14:19] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 20:14:19] application.DEBUG: < 200 [] []
[2017-08-31 20:14:31] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:14:31] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:14:31] application.DEBUG: < 200 [] []
[2017-08-31 20:14:31] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 20:14:31] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-31 20:14:31] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 20:14:31] application.DEBUG: < 404 [] []
[2017-08-31 20:14:31] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 20:14:31] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-31 20:14:31] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 20:14:31] application.DEBUG: < 404 [] []
[2017-08-31 20:14:39] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:14:39] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:14:39] application.DEBUG: < 200 [] []
[2017-08-31 20:14:43] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:14:43] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:14:43] application.DEBUG: < 200 [] []
[2017-08-31 20:14:45] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 20:14:45] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 20:14:45] application.DEBUG: < 200 [] []
[2017-08-31 20:15:08] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 20:15:08] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 20:15:08] application.DEBUG: < 200 [] []
[2017-08-31 20:16:10] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 20:16:10] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 20:16:10] application.DEBUG: < 200 [] []
[2017-08-31 20:16:13] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:16:13] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:16:13] application.DEBUG: < 200 [] []
[2017-08-31 20:16:16] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"2","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/2","method":"GET"} []
[2017-08-31 20:16:16] application.DEBUG: > GET /courses/page/2 [] []
[2017-08-31 20:16:16] application.DEBUG: < 200 [] []
[2017-08-31 20:16:26] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"3","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/3","method":"GET"} []
[2017-08-31 20:16:26] application.DEBUG: > GET /courses/page/3 [] []
[2017-08-31 20:16:26] application.DEBUG: < 200 [] []
[2017-08-31 20:16:34] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"2","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/2","method":"GET"} []
[2017-08-31 20:16:34] application.DEBUG: > GET /courses/page/2 [] []
[2017-08-31 20:16:34] application.DEBUG: < 200 [] []
[2017-08-31 20:16:38] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"3","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/3","method":"GET"} []
[2017-08-31 20:16:38] application.DEBUG: > GET /courses/page/3 [] []
[2017-08-31 20:16:38] application.DEBUG: < 200 [] []
[2017-08-31 20:16:40] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"4","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/4","method":"GET"} []
[2017-08-31 20:16:40] application.DEBUG: > GET /courses/page/4 [] []
[2017-08-31 20:16:40] application.DEBUG: < 200 [] []
[2017-08-31 20:18:32] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"4","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/4","method":"GET"} []
[2017-08-31 20:18:32] application.DEBUG: > GET /courses/page/4 [] []
[2017-08-31 20:18:32] application.DEBUG: < 200 [] []
[2017-08-31 20:18:35] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"2","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/2","method":"GET"} []
[2017-08-31 20:18:35] application.DEBUG: > GET /courses/page/2 [] []
[2017-08-31 20:18:35] application.DEBUG: < 200 [] []
[2017-08-31 20:18:40] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:18:40] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:18:40] application.DEBUG: < 200 [] []
[2017-08-31 20:34:47] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 20:34:47] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 20:34:47] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 20:34:47] application.DEBUG: < 404 [] []
[2017-08-31 20:43:15] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 20:43:15] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 20:43:15] application.DEBUG: < 200 [] []
[2017-08-31 20:43:17] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"2","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/2","method":"GET"} []
[2017-08-31 20:43:17] application.DEBUG: > GET /courses/page/2 [] []
[2017-08-31 20:43:17] application.DEBUG: < 200 [] []
[2017-08-31 20:43:33] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"5","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/5","method":"GET"} []
[2017-08-31 20:43:33] application.DEBUG: > GET /courses/page/5 [] []
[2017-08-31 20:43:33] application.DEBUG: < 200 [] []
[2017-08-31 20:43:39] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:43:39] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:43:39] application.DEBUG: < 200 [] []
[2017-08-31 20:43:43] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 20:43:43] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 20:43:43] application.DEBUG: < 200 [] []
[2017-08-31 20:44:00] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"1","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/1","method":"GET"} []
[2017-08-31 20:44:00] application.DEBUG: > GET /courses/page/1 [] []
[2017-08-31 20:44:00] application.DEBUG: < 200 [] []
[2017-08-31 20:44:02] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"3","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/3","method":"GET"} []
[2017-08-31 20:44:02] application.DEBUG: > GET /courses/page/3 [] []
[2017-08-31 20:44:02] application.DEBUG: < 200 [] []
[2017-08-31 20:44:02] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 20:44:02] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-31 20:44:02] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 20:44:02] application.DEBUG: < 404 [] []
[2017-08-31 20:44:05] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"4","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/4","method":"GET"} []
[2017-08-31 20:44:05] application.DEBUG: > GET /courses/page/4 [] []
[2017-08-31 20:44:05] application.DEBUG: < 200 [] []
[2017-08-31 20:45:16] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"3","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/3","method":"GET"} []
[2017-08-31 20:45:16] application.DEBUG: > GET /courses/page/3 [] []
[2017-08-31 20:45:16] application.DEBUG: < 200 [] []
[2017-08-31 20:46:41] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 20:46:41] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 20:46:41] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 20:46:41] application.DEBUG: < 404 [] []
[2017-08-31 20:49:29] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"4","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/4","method":"GET"} []
[2017-08-31 20:49:29] application.DEBUG: > GET /courses/page/4 [] []
[2017-08-31 20:49:29] application.DEBUG: < 200 [] []
[2017-08-31 20:50:05] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"4","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/4","method":"GET"} []
[2017-08-31 20:50:05] application.DEBUG: > GET /courses/page/4 [] []
[2017-08-31 20:50:05] application.DEBUG: < 200 [] []
[2017-08-31 20:56:25] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:56:25] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:56:25] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT c.id, COUNT(*) FROM courses c LIMIT 3 OFFSET 0':  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "c.id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT c.id, COUNT(*) FROM courses c LIMIT 3 OFFSET 0                ^ (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT c.id, COUNT(*) FROM courses c LIMIT 3 OFFSET 0':\n\nSQLSTATE[42803]: Grouping error: 7 ERROR:  column \"c.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT c.id, COUNT(*) FROM courses c LIMIT 3 OFFSET 0\n               ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 42803): SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"c.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT c.id, COUNT(*) FROM courses c LIMIT 3 OFFSET 0\n               ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42803): SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"c.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT c.id, COUNT(*) FROM courses c LIMIT 3 OFFSET 0\n               ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-08-31 20:56:25] application.ERROR: An exception occurred while executing 'SELECT c.id, COUNT(*) FROM courses c LIMIT 3 OFFSET 0':  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "c.id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT c.id, COUNT(*) FROM courses c LIMIT 3 OFFSET 0                ^ [] []
[2017-08-31 20:56:25] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT c.id, CO...', Array) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): Doctrine\DBAL\Connection->executeQuery('SELECT c.id, CO...', Array, Array) #3 /var/www/html/app/src/App/Services/CoursesService.php(29): Doctrine\DBAL\Query\QueryBuilder->execute() #4 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->getPaginated(3, 0) #5 [internal function]: App\Controllers\CoursesController->getPaginated('0') #6 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/app/web/index.php(23): Silex\Application->run() #11 {main} [] []
[2017-08-31 20:56:25] application.DEBUG: < 500 [] []
[2017-08-31 20:56:49] application.INFO: Matched route "{route}". {"route":"GET_courses_page_page","route_parameters":{"_controller":"courses.controller:getPaginated","page":"0","_route":"GET_courses_page_page"},"request_uri":"http://localhost:8000/courses/page/0","method":"GET"} []
[2017-08-31 20:56:49] application.DEBUG: > GET /courses/page/0 [] []
[2017-08-31 20:56:49] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 20:56:49] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-31 20:56:49] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 20:56:49] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT *, COUNT(*) FROM courses c LIMIT 3 OFFSET 0':  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "c.id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT *, COUNT(*) FROM courses c LIMIT 3 OFFSET 0                ^ (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT *, COUNT(*) FROM courses c LIMIT 3 OFFSET 0':\n\nSQLSTATE[42803]: Grouping error: 7 ERROR:  column \"c.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT *, COUNT(*) FROM courses c LIMIT 3 OFFSET 0\n               ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 42803): SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"c.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT *, COUNT(*) FROM courses c LIMIT 3 OFFSET 0\n               ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42803): SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"c.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT *, COUNT(*) FROM courses c LIMIT 3 OFFSET 0\n               ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-08-31 20:56:49] application.ERROR: An exception occurred while executing 'SELECT *, COUNT(*) FROM courses c LIMIT 3 OFFSET 0':  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "c.id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT *, COUNT(*) FROM courses c LIMIT 3 OFFSET 0                ^ [] []
[2017-08-31 20:56:49] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT *, COUNT...', Array) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): Doctrine\DBAL\Connection->executeQuery('SELECT *, COUNT...', Array, Array) #3 /var/www/html/app/src/App/Services/CoursesService.php(29): Doctrine\DBAL\Query\QueryBuilder->execute() #4 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->getPaginated(3, 0) #5 [internal function]: App\Controllers\CoursesController->getPaginated('0') #6 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/app/web/index.php(23): Silex\Application->run() #11 {main} [] []
[2017-08-31 20:56:49] application.DEBUG: < 404 [] []
[2017-08-31 20:56:49] application.DEBUG: < 500 [] []
[2017-08-31 21:14:52] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 21:14:52] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 21:14:52] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 21:14:52] application.DEBUG: < 404 [] []
[2017-08-31 21:26:59] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-31 21:26:59] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-31 21:26:59] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-31 21:26:59] application.DEBUG: < 404 [] []
