[2017-09-01 19:01:58] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-09-01 19:01:58] application.ERROR: No route found for "GET /" [] []
[2017-09-01 19:01:58] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 19:01:58] application.DEBUG: < 404 [] []
[2017-09-01 19:01:58] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-09-01 19:01:58] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-09-01 19:01:58] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 19:01:58] application.DEBUG: < 404 [] []
[2017-09-01 19:01:58] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-09-01 19:01:58] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-09-01 19:01:58] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 19:01:58] application.DEBUG: < 404 [] []
[2017-09-01 19:01:58] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (from "http://localhost:8001/") (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8001/\") at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-09-01 19:01:58] application.ERROR: No route found for "GET /favicon.ico" (from "http://localhost:8001/") [] []
[2017-09-01 19:01:58] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 19:01:58] application.DEBUG: < 404 [] []
[2017-09-01 19:03:41] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "GET /": Method Not Allowed (Allow: POST) (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /\": Method Not Allowed (Allow: POST) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-09-01 19:03:41] application.ERROR: No route found for "GET /": Method Not Allowed (Allow: POST) [] []
[2017-09-01 19:03:41] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 19:03:41] application.DEBUG: < 405 [] []
[2017-09-01 19:03:52] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "GET /": Method Not Allowed (Allow: POST) (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /\": Method Not Allowed (Allow: POST) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-09-01 19:03:52] application.ERROR: No route found for "GET /": Method Not Allowed (Allow: POST) [] []
[2017-09-01 19:03:52] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 19:03:52] application.DEBUG: < 405 [] []
[2017-09-01 19:03:52] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-09-01 19:03:52] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-09-01 19:03:52] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 19:03:52] application.DEBUG: < 404 [] []
[2017-09-01 19:04:03] application.INFO: Matched route "{route}". {"route":"GET_","route_parameters":{"_controller":"courses.controller:index","_route":"GET_"},"request_uri":"http://localhost:8001/","method":"GET"} []
[2017-09-01 19:04:03] application.DEBUG: > GET / [] []
[2017-09-01 19:04:03] application.DEBUG: < 200 [] []
[2017-09-01 19:10:01] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:10:01] application.DEBUG: > POST /courses [] []
[2017-09-01 19:10:06] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:10:06] application.DEBUG: > POST /courses [] []
[2017-09-01 19:11:05] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:11:05] application.DEBUG: > POST /courses [] []
[2017-09-01 19:11:05] application.DEBUG: < 200 [] []
[2017-09-01 19:11:20] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:11:20] application.DEBUG: > POST /courses [] []
[2017-09-01 19:11:20] application.DEBUG: < 200 [] []
[2017-09-01 19:11:49] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:11:49] application.DEBUG: > POST /courses [] []
[2017-09-01 19:11:49] application.DEBUG: < 200 [] []
[2017-09-01 19:25:33] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:25:33] application.DEBUG: > POST /courses [] []
[2017-09-01 19:25:33] application.DEBUG: < 200 [] []
[2017-09-01 19:26:37] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:26:37] application.DEBUG: > POST /courses [] []
[2017-09-01 19:26:37] application.DEBUG: < 201 [] []
[2017-09-01 19:27:13] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:27:13] application.DEBUG: > POST /courses [] []
[2017-09-01 19:27:13] application.DEBUG: < 201 [] []
[2017-09-01 19:27:29] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:27:29] application.DEBUG: > POST /courses [] []
[2017-09-01 19:27:29] application.DEBUG: < 201 [] []
[2017-09-01 19:28:57] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:28:57] application.DEBUG: > POST /courses [] []
[2017-09-01 19:28:57] application.DEBUG: < 201 [] []
[2017-09-01 19:29:22] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:29:22] application.DEBUG: > POST /courses [] []
[2017-09-01 19:29:22] application.DEBUG: < 201 [] []
[2017-09-01 19:29:38] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:29:38] application.DEBUG: > POST /courses [] []
[2017-09-01 19:29:38] application.DEBUG: < 201 [] []
[2017-09-01 19:29:51] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:29:51] application.DEBUG: > POST /courses [] []
[2017-09-01 19:29:51] application.DEBUG: < 201 [] []
[2017-09-01 19:30:16] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:30:16] application.DEBUG: > POST /courses [] []
[2017-09-01 19:30:16] application.DEBUG: < 201 [] []
[2017-09-01 19:30:45] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:30:45] application.DEBUG: > POST /courses [] []
[2017-09-01 19:30:45] application.DEBUG: < 201 [] []
[2017-09-01 19:32:59] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:32:59] application.DEBUG: > POST /courses [] []
[2017-09-01 19:32:59] application.DEBUG: < 201 [] []
[2017-09-01 19:33:00] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:33:00] application.DEBUG: > POST /courses [] []
[2017-09-01 19:33:00] application.DEBUG: < 201 [] []
[2017-09-01 19:43:16] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:43:16] application.DEBUG: > POST /courses [] []
[2017-09-01 19:43:16] application.DEBUG: < 201 [] []
[2017-09-01 19:43:40] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:43:40] application.DEBUG: > POST /courses [] []
[2017-09-01 19:43:40] application.DEBUG: < 201 [] []
[2017-09-01 19:44:02] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:44:02] application.DEBUG: > POST /courses [] []
[2017-09-01 19:51:23] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:51:23] application.DEBUG: > POST /courses [] []
[2017-09-01 19:51:51] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:51:51] application.DEBUG: > POST /courses [] []
[2017-09-01 19:53:25] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 19:53:25] application.DEBUG: > POST /courses [] []
[2017-09-01 20:04:01] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:04:01] application.DEBUG: > POST /courses [] []
[2017-09-01 20:04:01] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:04:01] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:04:01] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(694): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/src/App/Services/CoursesService.php(10): Doctrine\DBAL\Connection->insert('courses', Array) #5 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->save(Array) #6 [internal function]: App\Controllers\CoursesController->save(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/app/web/index.php(23): Silex\Application->run() #12 {main} [] []
[2017-09-01 20:04:01] application.DEBUG: < 500 [] []
[2017-09-01 20:04:41] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:04:41] application.DEBUG: > POST /courses [] []
[2017-09-01 20:04:41] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:04:41] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:04:41] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(694): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/src/App/Services/CoursesService.php(10): Doctrine\DBAL\Connection->insert('courses', Array) #5 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->save(Array) #6 [internal function]: App\Controllers\CoursesController->save(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/app/web/index.php(23): Silex\Application->run() #12 {main} [] []
[2017-09-01 20:04:41] application.DEBUG: < 500 [] []
[2017-09-01 20:05:06] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:05:06] application.DEBUG: > POST /courses [] []
[2017-09-01 20:05:06] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:05:06] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:05:06] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(694): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/src/App/Services/CoursesService.php(10): Doctrine\DBAL\Connection->insert('courses', Array) #5 /var/www/html/app/src/App/Controllers/CoursesController.php(34): App\Services\CoursesService->save(Array) #6 [internal function]: App\Controllers\CoursesController->save(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/app/web/index.php(23): Silex\Application->run() #12 {main} [] []
[2017-09-01 20:05:06] application.DEBUG: < 500 [] []
[2017-09-01 20:05:17] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:05:17] application.DEBUG: > POST /courses [] []
[2017-09-01 20:06:00] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:06:00] application.DEBUG: > POST /courses [] []
[2017-09-01 20:09:24] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:09:24] application.DEBUG: > POST /courses [] []
[2017-09-01 20:09:24] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:09:24] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:09:24] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(694): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/src/App/Services/CoursesService.php(10): Doctrine\DBAL\Connection->insert('courses', Array) #5 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->save(Array) #6 [internal function]: App\Controllers\CoursesController->save(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/app/web/index.php(23): Silex\Application->run() #12 {main} [] []
[2017-09-01 20:09:24] application.DEBUG: < 500 [] []
[2017-09-01 20:09:50] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:09:50] application.DEBUG: > POST /courses [] []
[2017-09-01 20:09:50] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:09:50] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:09:50] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(694): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/src/App/Services/CoursesService.php(10): Doctrine\DBAL\Connection->insert('courses', Array) #5 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->save(Array) #6 [internal function]: App\Controllers\CoursesController->save(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/app/web/index.php(23): Silex\Application->run() #12 {main} [] []
[2017-09-01 20:09:50] application.DEBUG: < 500 [] []
[2017-09-01 20:10:07] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:10:07] application.DEBUG: > POST /courses [] []
[2017-09-01 20:10:07] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:10:07] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:10:07] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(694): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/src/App/Services/CoursesService.php(10): Doctrine\DBAL\Connection->insert('courses', Array) #5 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->save(Array) #6 [internal function]: App\Controllers\CoursesController->save(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/app/web/index.php(23): Silex\Application->run() #12 {main} [] []
[2017-09-01 20:10:07] application.DEBUG: < 500 [] []
[2017-09-01 20:10:32] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:10:32] application.DEBUG: > POST /courses [] []
[2017-09-01 20:13:57] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:13:57] application.DEBUG: > POST /courses [] []
[2017-09-01 20:13:57] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:13:57] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:13:57] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(694): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/src/App/Services/CoursesService.php(10): Doctrine\DBAL\Connection->insert('courses', Array) #5 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->save(Array) #6 [internal function]: App\Controllers\CoursesController->save(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/app/web/index.php(23): Silex\Application->run() #12 {main} [] []
[2017-09-01 20:13:57] application.DEBUG: < 500 [] []
[2017-09-01 20:16:03] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:16:03] application.DEBUG: > POST /courses [] []
[2017-09-01 20:16:03] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:16:03] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:16:03] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(694): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/src/App/Services/CoursesService.php(10): Doctrine\DBAL\Connection->insert('courses', Array) #5 /var/www/html/app/src/App/Controllers/CoursesController.php(33): App\Services\CoursesService->save(Array) #6 [internal function]: App\Controllers\CoursesController->save(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/app/web/index.php(23): Silex\Application->run() #12 {main} [] []
[2017-09-01 20:16:03] application.DEBUG: < 500 [] []
[2017-09-01 20:16:14] application.INFO: Matched route "{route}". {"route":"GET_","route_parameters":{"_controller":"courses.controller:index","_route":"GET_"},"request_uri":"http://localhost:8001/","method":"GET"} []
[2017-09-01 20:16:14] application.DEBUG: > GET / [] []
[2017-09-01 20:16:14] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-09-01 20:16:14] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-09-01 20:16:14] application.DEBUG: < 200 [] []
[2017-09-01 20:16:14] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 20:16:14] application.DEBUG: < 404 [] []
[2017-09-01 20:16:18] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8001/courses","method":"GET"} []
[2017-09-01 20:16:18] application.DEBUG: > GET /courses [] []
[2017-09-01 20:16:18] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-09-01 20:16:18] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-09-01 20:16:18] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(16): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(49): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(23): Silex\Application->run() #13 {main} [] []
[2017-09-01 20:16:18] application.DEBUG: < 500 [] []
[2017-09-01 20:26:30] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8001/courses","method":"GET"} []
[2017-09-01 20:26:30] application.DEBUG: > GET /courses [] []
[2017-09-01 20:26:30] application.DEBUG: < 200 [] []
[2017-09-01 20:26:36] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:26:36] application.DEBUG: > POST /courses [] []
[2017-09-01 20:26:51] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:26:51] application.DEBUG: > POST /courses [] []
[2017-09-01 20:26:51] application.DEBUG: < 201 [] []
[2017-09-01 20:27:03] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8001/courses","method":"GET"} []
[2017-09-01 20:27:03] application.DEBUG: > GET /courses [] []
[2017-09-01 20:27:03] application.DEBUG: < 200 [] []
[2017-09-01 20:27:35] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:27:35] application.DEBUG: > POST /courses [] []
[2017-09-01 20:32:16] application.INFO: Matched route "{route}". {"route":"POST_courses","route_parameters":{"_controller":"courses.controller:save","_route":"POST_courses"},"request_uri":"http://destination-service/courses","method":"POST"} []
[2017-09-01 20:32:16] application.DEBUG: > POST /courses [] []
[2017-09-01 20:32:16] application.DEBUG: < 201 [] []
[2017-09-01 20:32:21] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-09-01 20:32:21] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-09-01 20:32:21] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-09-01 20:32:21] application.DEBUG: < 404 [] []
[2017-09-01 20:32:21] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8001/courses","method":"GET"} []
[2017-09-01 20:32:21] application.DEBUG: > GET /courses [] []
[2017-09-01 20:32:21] application.DEBUG: < 200 [] []
